project:
  type: website

website:
  title: "ai:dolescence"
  site-url: "https://aidolescence.cz/"
  
  navbar:
    background: primary
    right:
      - icon: house-door-fill
        text: " "
        href: index.qmd
      - text: "Cíl"
        href: "#sekce-cil"
      - text: "Přínos"
        href: "#sekce-prinos"
      - text: "Informovaný souhlas"
        href: "#sekce-souhlas"
      - text: "Sběr dat"
        href: "#sekce-faze"
      - text: "Výsledky výzkumu"
        href: vysledky_vyzkumu.qmd
      - text: "Kontakty"
        href: "#sekce-kontakt"
        

  page-footer: 
    
    background: light
    border: false
    left: "ai:dolescence, ©2025"
    right: 
      - icon: youtube 
        href: https://www.youtube.com/@aidolescence
      - icon: facebook 
        href: https://facebook.com/

    

format:
  html:
    theme: minty
    include-after-body: _include-after.html
    css: styles.css
    toc: false

