project:
  type: website

website:
  title: "ai:dolescence"
  site-url: "https://aidolescence.cz/"
  
  navbar:
    background: primary
    right:
      - icon: house-door-fill
        text: " "
        href: index.qmd
      - text: "Cíl výzkumu"
        href: cil_vyzkumu.qmd
      - text: "Sběr dat"
        href: sber_dat.qmd
      - text: "Přínos projektu"
        href: prinos_projektu.qmd
      - text: "Výsledky výzkumu"
        href: vysledky_vyzkumu.qmd
        
  search: 
    location: navbar
    type: textbox
  
  back-to-top-navigation: true
  
  page-footer: 
    
    background: light
    border: false
    left: "ai:dolescence, ©2025"
    right: 
      - icon: youtube 
        href: https://youtube.com/
      - icon: twitter 
        href: https://twitter.com/
      - icon: facebook 
        href: https://facebook.com/
      - icon: github
        href: https://github.com/

    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false



