project:
  type: website

website:
  title: "ai:dolescence"
  site-url: "https://aidolescence.cz/"
  
  navbar:
    background: primary
    right:
      - icon: house-door-fill
        text: " "
        href: index.qmd
      - text: "O projektu"
        href: "#sekce-o_projektu"
      - text: "Náš tým"
        href: "#sekce-tym"
      - text: "Sběr dat"
        href: "#sekce-faze"
      - text: "Informovaný souhlas"
        href: "#sekce-souhlas"
      - text: "Výsledky výzkumu"
        href: "#sekce-vysledky"
      - text: "Kontakty"
        href: "#sekce-kontakt"
        

  page-footer: 
    
    background: light
    border: false
    left: "ai:dolescence, ©2025"
    right: 
      - icon: youtube 
        href: https://www.youtube.com/@aidolescence
      - icon: facebook 
        href: https://www.facebook.com/profile.php?id=61579209989350

    

format:
  html:
    theme: minty
    include-after-body: _include-after.html
    css: styles.css
    toc: false

